---
  - name: install supervisor package
    apt: pkg=supervisor state=present
    tags:
      - supervisor
      - packages

  - name: set supervisorctl config
    template: src=../templates/supervisord.conf.j2 dest=/etc/supervisor/supervisord.conf owner=root group=root
    notify: restart supervisor
    tags:
      - supervisor
      - config

  - name: enable supervisorctl service
    service: name=supervisor enabled=yes
    tags:
      - supervisor