---
  - name: Add contrib repos if Linux dist is Debian
    lineinfile: dest=/etc/apt/sources.list line="deb http://http.us.debian.org/debian stable main contrib"
    when: ansible_distribution == "Debian"

  - name: Add non-free repos if Linux dist is Debian
    lineinfile: dest=/etc/apt/sources.list line="deb http://http.us.debian.org/debian stable main contrib non-free"
    when: ansible_distribution == "Debian"

  - name: update apt cache
    apt: update_cache=yes
    tags: 
      - common
      - update_packages

  - name: upgrade apt cache
    apt: upgrade=full
    tags: 
      - common
      - update_packages

  - name: install common packages
    apt: pkg={{item}} state=present
    with_items:
      - vim
      - htop
      - screen
      - git
      - mailutils
      - unzip
      - sudo
    tags: 
      - common
      - packages

  - name: change hostname
    hostname: name="{{ server_hostname }}"
    tags: common
    notify:
      - restart hostname

