---
  - name: Add contrib repos if Linux dist is Debian
    lineinfile: dest=/etc/apt/sources.list line="deb http://http.us.debian.org/debian stable main contrib"
    when: ansible_distribution == "Debian"

  - name: Add non-free repos if Linux dist is Debian
    lineinfile: dest=/etc/apt/sources.list line="deb http://http.us.debian.org/debian stable main contrib non-free"
    when: ansible_distribution == "Debian"

  - name: update apt cache
    apt: update_cache=yes
    tags: 
      - common
      - update_packages

  - name: install aptitude
    apt: pkg={{item}} state=present
    with_items:
      - aptitude
    tags:
      - common
      - packages

  - name: upgrade apt cache
    apt: upgrade=full
    tags: 
      - common
      - update_packages


  - name: Install common packages
    apt: pkg={{item}} state=present
    with_items:
      - vim
      - htop
      - screen
      - git
      - unzip
      - sudo
      - tree
      - python-pip
      - python3-pip
      - python-dev
      - python3-dev
      - python-psutil
      - mailutils
      - curl
    tags:
      - common
      - packages

  - name: Install python enviornment
    pip: name={{item}}
    with_items:
      - virtualenv
      - thefuck
    tags:
      - common
      - packages

  - name: change hostname
    hostname: name="{{ hostname }}"
    when: hostname is defined and server_hostname is not defined
    tags: common
    notify:
      - restart hostname


  - name: change hostname
    hostname: name="{{ server_hostname }}"
    when: server_hostname is defined
    tags: common
    notify:
      - restart hostname

  - name: locale gen
    locale_gen: name={{ locale | default('en_GB.UTF-8') }} state=present
    tags:
      - common

  - name: Set locales
    template: src=../templates/locale.j2 dest=/etc/default/locale
    tags:
      - common

  - name: create /root/.ssh directory
    file: path=/root/.ssh state=directory mode=0700
    when: root_ssh_key is defined
    tags:
      - common

  - name: copy root ssh key
    copy: src=../../../files/ssh_keys/{{root_ssh_key}} dest="/root/.ssh/id_rsa" mode=400 owner=root group=root
    when: root_ssh_key is defined
    tags:
      - common

  - name: copy root ssh key
    copy: src=../../../files/ssh_keys/{{root_ssh_key}}.pub dest="/root/.ssh/id_rsa.pub" mode=644 owner=root group=root
    when: root_ssh_key is defined
    tags:
      - common

  - name: insert authorized ssh keys if exist
    authorized_key: user=root key="{{item}}"
    with_items: "{{root_authorized_keys}}"
    when: root_authorized_keys is defined
    tags:
      - common
