  - name: install fail2ban package
    apt: name={{item}} state=installed update_cache=yes
    with_items:
      - fail2ban
      - python-pyinotify
      - ipset
    tags:
      - fail2ban
      - packages

  - name: remove previous jail.d configurations
    file: path=/etc/fail2ban/jail.d state=absent

  - name: create jail.d empty folder
    file: path=/etc/fail2ban/jail.d state=directory mode=0755 owner=root group=root

  - name: set up fail2ban config
    template: src=../templates/jail.local.j2 dest=/etc/fail2ban/jail.local mode=0422 owner=root group=root

  - name: shh jail
    template: src=../templates/ssh.conf.j2 dest=/etc/fail2ban/jail.d/ssh.conf mode=0422 owner=root group=root
    when: fail2ban_ssh is defined

  - name: shh-ddos jail
    template: src=../templates/ssh-ddos.conf.j2 dest=/etc/fail2ban/jail.d/ssh-ddos.conf mode=0422 owner=root group=root
    when: fail2ban_sshddos is defined

  - name: shh-route jail
    template: src=../templates/ssh-route.conf.j2 dest=/etc/fail2ban/jail.d/ssh-route.conf mode=0422 owner=root group=root
    when: fail2ban_sshroute is defined

  - name: ssh-iptables-ipset4 jail
    template: src=../templates/ssh-iptables-ipset4.conf.j2 dest=/etc/fail2ban/jail.d/ssh-iptables-ipset4.conf mode=0422 owner=root group=root
    when: fail2ban_sshipset4 is defined

  - name: ssh-iptables-ipset6 jail
    template: src=../templates/ssh-iptables-ipset6.conf.j2 dest=/etc/fail2ban/jail.d/ssh-iptables-ipset6.conf mode=0422 owner=root group=root
    when: fail2ban_sshipset6 is defined

  - name: apache jail
    template: src=../templates/apache2.conf.j2 dest=/etc/fail2ban/jail.d/apache2.conf mode=0422 owner=root group=root
    when: fail2ban_apache is defined

  - name: apache-overflow jail
    template: src=../templates/apache-overflows.conf.j2 dest=/etc/fail2ban/jail.d/apache-overflows.conf mode=0422 owner=root group=root
    when: fail2ban_apacheoverflow is defined

  - name: apache-badbots jail
    template: src=../templates/apache-badbots.conf.j2 dest=/etc/fail2ban/jail.d/apache-badbots.conf mode=0422 owner=root group=root
    when: fail2ban_apacheoverflow is defined

  - name: apache-nohome jail
    template: src=../templates/apache-nohome.conf.j2 dest=/etc/fail2ban/jail.d/apache-nohome.conf mode=0422 owner=root group=root
    when: fail2ban_apachenohome is defined

  - name: php-url-fopen jail
    template: src=../templates/php-url-fopen.conf.j2 dest=/etc/fail2ban/jail.d/php-url-fopen.conf mode=0422 owner=root group=root
    when: fail2ban_phpurlfopen is defined

  - name: enable fail2ban
    service: name=fail2ban enabled=yes

  - name: restart fail2ban
    debug: msg="restart fail2ban"
    notify: restart fail2ban