Vagrant.configure("2") do |config|
  config.vm.network "public_network"

  config.vm.define :ubuntu1 do |ubuntu_config|
    ubuntu_config.vm.box = "ubuntu/xenial64"
    ubuntu_config.vm.hostname = "Ubuntu1"
    ubuntu_config.vm.provider "virtualbox" do |vb|
            vb.memory = "512"
    end
    ubuntu_config.vm.provision :shell, path: "bootstrap.sh"
   end
end