---

  - hosts: test

    vars_files:
      - ../../vars/target_hosts/test.yml

    roles:
      - { role: ../../roles/common_setup}
      - { role: ../../roles/create_user}
      - { role: ../../roles/keyscan}
      - { role: ../../roles/apache_setup}
      - { role: ../../roles/php_setup}