  - name: add docker repository if it is Debian
    apt_repository: repo='deb http://http.debian.net/debian wheezy-backports main' state=present
    when: ansible_distribution == "Debian"
    tags:
      - docker_setup
      - packages

  - name: install docker required packages
    apt: pkg={{item}} state=present
    with_items:
      - apt-transport-https
      - ca-certificates
    tags:
      - docker_setup
      - packages

  - name: install linux-image-extra (Ubuntu)
    apt: pkg={{item}} state=present
    with_items:
      - linux-image-extra-{{ ansible_kernel }}
      - linux-image-extra-virtual
    when: ansible_distribution == "Ubuntu"
    tags:
      - docker_setup
      - packages

  - name: Add docker key
    shell: apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
    tags:
      - docker_setup
      - packages

  - name: remove old file /etc/apt/sources.list.d/docker.list
    file: path=/etc/apt/sources.list.d/docker.list state=absent
    tags:
      - docker_setup
      - packages

  - name: create file /etc/apt/sources.list.d/docker.list
    file: path=/etc/apt/sources.list.d/docker.list state=touch
    tags:
      - docker_setup
      - packages

  - name: Add entry (Debian)
    lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo debian-wheezy main" state=present
    when: ansible_distribution == "Debian"
    tags:
      - docker_setup
      - packages

  - name: Add entry (Ubuntu 14.04)
    lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo ubuntu-trusty main" state=present
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "14.04"
    tags:
      - docker_setup
      - packages

  - name: Add entry (Ubuntu 16.04)
    lineinfile: dest=/etc/apt/sources.list.d/docker.list line="deb https://apt.dockerproject.org/repo ubuntu-xenial main" state=present
    when: ansible_distribution == "Ubuntu" and ansible_distribution_version == "16.04"
    tags:
      - docker_setup
      - packages

  - name: update apt cache
    apt: update_cache=yes
    tags:
      - docker_setup
      - update_packages

  - name: install docker
    apt: pkg={{item}} state=present
    with_items:
      - docker-engine
    tags:
      - docker_setup
      - packages

  - name: enable docker
    service: name=docker state=running

  - name: install docker-compose
    get_url: url=https://github.com/docker/compose/releases/download/1.8.0/docker-compose-Linux-x86_64 dest=/usr/local/bin/docker-compose validate_certs=no mode=0755 owner=root group=root

