---
  - name: Install laravel for required users
    shell: su {{item.username}} -c 'composer global require "laravel/installer"'
    with_items: users
    when: item.install_laravel is defined
    tags:
      - laravel

  - name: Add laravel to user's PATH - Ubuntu
    lineinfile: dest={{item.home if item.home is defined else '/home/'+item.username}}/.bashrc line="PATH=\"$PATH:$HOME/.config/composer/vendor/bin\""
    with_items: users
    when: item.install_laravel is defined and ansible_distribution == "Ubuntu" and ansible_distribution_release == 'trusty'
    tags:
      - laravel

  - name: Add laravel to user's PATH - Debian
    lineinfile: dest={{item.home if item.home is defined else '/home/'+item.username}}/.bashrc line="PATH=\"$PATH:$HOME/.composer/vendor/bin\""
    with_items: users
    when: item.install_laravel is defined and ansible_distribution == "Debian" and ansible_distribution_release == 'jessie'
    tags:
      - laravel